Fixes some
grijul/zauth pull request #1
Opened 2021-08-18 07:23 UTC by mattn

* Use `path/filepath` instead of `path`
* Call `strings.TrimSpace` before checking empty since Windows return `\r\n`
* Use $USERPROFILE instead $HOME on Windows

2021-08-18 08:01 UTC, grijul commented
Thank you for your contribution. Let me review the changes (file changes looks good) and I'll merge.

2021-08-18 16:28 UTC, grijul requested changes
Thank you for your time and effort. Overall looks good. Once we resolve the comments, this is good to merge.

2021-08-18 16:28 UTC, grijul commented on internal/args/args.go
> +	tbl.WithWidthFunc(runewidth.StringWidth)
Why are we using WithWidthFunc() here? Is this trying to solve any particular usecase?
As per documentation: _WithWidthFunc sets the function used to calculate the width of the string in a column. By default, the number of utf8 runes in the string is used_

Seems like default should suffice .. Am I missing something?

2021-08-20 02:22 UTC, mattn commented on internal/args/args.go
> +	tbl.WithWidthFunc(runewidth.StringWidth)
String Width is not same as Rune Count. For example `あ` have 2 cells in terminal but count of runes is 1. `runewidth.StringWidth` return 2.

2021-08-20 09:22 UTC, grijul commented on internal/args/args.go
> +	tbl.WithWidthFunc(runewidth.StringWidth)
Got it! Thanks!

2021-08-20 09:22 UTC, grijul approved these changes

2021-08-20 09:22 UTC, merged